[package]
name = "apool"
version = "0.1.0"
edition = "2018"

[dependencies]
smallvec = "1.6.1"

[dependencies.tokio]
version = "1.10.0"
features = ["rt", "sync"]
optional = true

[features]
default = ["tokio"]

